enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "6.42.54"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Custom package name' 'Enable debug logging'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "auto"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Enable debug logging' 'Custom branding heading'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
